# yazi.toml
# [mgr]
# show_hidden = true

[opener]
play = [
    { run = 'mpv "$@"', orphan = true, for = "unix"}
]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
]

[open]
rules = [
	{ mime = "text/*", use = "edit" },
	{ mime = "video/*", use = "play" },

	# { mime = "application/json", use = "edit" },
	{ name = "*.json", use = "edit" },
	{ name = "*.json", use = "edit" },
    { name = "*.md", use = "edit" },
    { name = "*.txt", use = "edit" },
    { name = "*.mp4", use = "play" },
    { name = "*.mkv", use = "play" },

	# Multiple openers for a single rule
	{ name = "*.html", use = [ "open", "edit" ] },
]